#!/bin/bash

URL=${1}

XSOCK=/tmp/.X11-unix
export DISPLAY=unix:0

CONTAINER=dougborg/rpi-chrometainer
IMAGE_NAME=chrometainer

xhost +

# Run an ephemeral chromium container
docker run -rm \
  -v ${XSOCK}:${XSOCK} \
  -e DISPLAY=${DISPLAY} \
  --restart=on-failure:5 \
  --privileged=true \
  --name ${IMAGE_NAME} \
  ${CONTAINER} --app="${URL}"
